# Generated by Django 4.1.1 on 2023-03-07 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_follower_count_user_following_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follower_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following_count',
        ),
    ]
