# Generated by Django 4.1.1 on 2023-03-07 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_user_follower_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes_count',
        ),
    ]
