# Generated by Django 4.1.1 on 2023-03-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_post_likes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cautions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='important_things_to_take',
            field=models.TextField(blank=True, default=''),
        ),
    ]
