# Generated by Django 4.1.1 on 2023-03-12 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_postimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImages',
        ),
    ]
