# Generated by Django 4.1.1 on 2023-03-13 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_postimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
