# Generated by Django 4.1.1 on 2023-03-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_postimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='staying_place_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='post',
            name='trip_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
