# Generated by Django 4.1.1 on 2023-03-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trips_reviewed',
            field=models.IntegerField(default=0),
        ),
    ]
