# Generated by Django 4.1.1 on 2023-03-27 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_user_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_pic',
            new_name='pfp',
        ),
    ]
