# Generated by Django 4.1.1 on 2023-03-29 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_notifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notifications',
        ),
    ]
