# Generated by Django 4.1.1 on 2023-03-29 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='related_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_post', to='api.post'),
        ),
    ]
