# Generated by Django 4.1.1 on 2023-03-29 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_notification_delete_notifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notification',
            new_name='notification_text',
        ),
    ]
