# Generated by Django 4.1.1 on 2023-04-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_rename_notification_notification_notification_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender_pfp_url',
            field=models.CharField(default='', max_length=256),
        ),
    ]
