# Generated by Django 4.1.1 on 2023-04-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_notification_sender_pfp_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='sender_pfp_url',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
