# Generated by Django 4.1.1 on 2023-04-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_notification_sender_pfp_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oauth_user',
            field=models.BooleanField(default=False),
        ),
    ]
