# Generated by Django 4.1.1 on 2023-04-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_user_oauth_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_pfp_link',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
