# Generated by Django 4.1.1 on 2023-04-10 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_blogcomments_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomments',
            name='blog',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.blog'),
        ),
    ]
