# Generated by Django 4.1.1 on 2023-04-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_remove_blogcomments_blog_remove_blogcomments_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='relevance_score',
            field=models.FloatField(default=0.0),
        ),
    ]
