# Generated by Django 4.1.1 on 2023-04-11 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_post_relevance_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='relevance_score',
        ),
    ]
