# Generated by Django 4.1.1 on 2023-04-11 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_post_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='oauth_user',
        ),
    ]
